jobs:
- job: 'GenerateDocs'
  trigger:
    - 4.x-current
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    BUILD_REASON: $(Build.Reason)
    BUILD_BRANCH: $(Build.SourceBranch)
  steps:
    - script: ./CI/generate-docs.sh
      displayName: 'Generate docs'

# - job: 'Build_Windows'
#   pool:
#     vmImage: 'windows-2019'
#   steps:
#     - checkout: self
#       submodules: true

- job: 'Build_Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self
      submodules: true

    - script: ./CI/install-dependencies-xenial.sh
      displayName: 'Install dependencies'

    - script: ./CI/build-xenial.sh
      displayName: 'Build obs-websocket'

    - script: ./CI/package-xenial.sh
      displayName: 'Package obs-websocket'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './package'
        artifactName: 'deb_build'

- job: 'Build_macOS'
  pool:
    vmImage: 'macos-10.14'
  steps:
    - checkout: self
      submodules: true

    - script: ./CI/install-dependencies-macos.sh
      displayName: 'Install dependencies'

    - script: ./CI/install-build-obs-macos.sh
      displayName: 'Build OBS'

    - script: ./CI/build-macos.sh
      displayName: 'Build obs-websocket'

    - script: ./CI/package-macos.sh
      displayName: 'Package obs-websocket'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './release'
        artifactName: 'macos_build'
