jobs:
- job: 'GenerateDocs'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/4.x-current')
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    BUILD_REASON: $(Build.Reason)
    BUILD_BRANCH: $(Build.SourceBranch)
  steps:
    - script: ./CI/generate-docs.sh
      displayName: 'Generate docs'

- job: 'Build_Windows'
  pool:
    vmImage: 'windows-2019'
  variables:
    build_config: RelWithDebInfo
    DepsBasePath: 'C:\obsdependencies'
    DepsPath32: '%DepsBasePath%\win32'
    DepsPath64: '%DepsBasePath%\win64'
    QtBaseDir: 'C:\QtDep'
    QTDIR32: '%QtBaseDir%\5.10.1\msvc2017'
    QTDIR64: '%QtBaseDir%\5.10.1\msvc2017_64'
  steps:
    - checkout: self
      submodules: true

    - script: ./CI/install-qt-win.cmd
      displayName: 'Install Qt'
      env:
        QtBaseDir: $(QtBaseDir)

    - script: ./CI/download-obs-deps.cmd
      displayName: 'Download OBS dependencies'

    - script: ./CI/install-build-obs-windows.cmd
      displayName: 'Build OBS 32-bit and 64-bit'
      env:
        build_config: $(build_config)
        DepsPath32: $(DepsPath32)
        DepsPath64: $(DepsPath64)
        QTDIR32: $(QTDIR32)
        QTDIR64: $(QTDIR64)

    - script: ./CI/prepare-cmake-windows.cmd
      displayName: 'CMake obs-websocket'
      env:
        build_config: $(build_config)
        QTDIR32: $(QTDIR32)
        QTDIR64: $(QTDIR64)

    - task: MSBuild@1
      displayName: 'Build obs-websocket 32-bit'
      inputs:
        msbuildArguments: '/m /p:Configuration=$(build_config)'
        solution: '.\build32\obs-studio.sln'

    - task: MSBuild@1
      displayName: 'Build obs-websocket 64-bit'
      inputs:
        msbuildArguments: '/m /p:Configuration=$(build_config)'
        solution: '.\build64\obs-studio.sln'

    # TODO package zip archive
    
    # TODO build installer

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './release'
        artifactName: 'windows_build'

- job: 'Build_Linux'
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
      BUILD_REASON: $(Build.Reason)
      BRANCH_SHORT_NAME: $(Build.SourceBranchName)
      BRANCH_FULL_NAME: $(Build.SourceBranch)
  steps:
    - checkout: self
      submodules: true

    - script: ./CI/install-dependencies-ubuntu.sh
      displayName: 'Install dependencies'

    - script: ./CI/build-ubuntu.sh
      displayName: 'Build obs-websocket'

    - script: ./CI/package-ubuntu.sh
      displayName: 'Package obs-websocket'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './package'
        artifactName: 'deb_build'

- job: 'Build_macOS'
  pool:
    vmImage: 'macos-10.13'
  steps:
    - checkout: self
      submodules: true

    - script: ./CI/install-dependencies-macos.sh
      displayName: 'Install dependencies'

    - script: ./CI/install-build-obs-macos.sh
      displayName: 'Build OBS'

    - script: ./CI/build-macos.sh
      displayName: 'Build obs-websocket'

    - script: ./CI/package-macos.sh
      displayName: 'Package obs-websocket'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './release'
        artifactName: 'macos_build'
